### ISSUE TITLE
No such file od directory /lib/modules

### ISSUE THREAD

**Issue by lzap** [ubccr/grendel-images#1]
Hey,

I am trying to build the image on Fedora 34, assuming that all the patches are now in the upstream, I simply checked out the repository and executed `mkosi` but getting:

```
 Building initrd with livenet support...

ls: cannot access '/lib/modules/*': No such file or directory
```

Is there anything else I need to do? Thanks!

Edit: I see the relevant patch is https://github.com/ubccr/mkosi/commit/04dc03071d1c484b6a83856b0e3f5ee03fa33a6e need to take a look

**Comment by lzap** [comment]
I guess the patch should be in (a different person fixed it however): https://github.com/systemd/mkosi/pull/432/files

So I guess I need to dig in why I am missing my kernel modules.

**Comment by lzap** [comment]
Apologies, I forgot to add the configuration, it was building non-bootable image :-)

The correct build command is indeed `sudo mkosi --default=./mkosi.files/mkosi.centos8`

**Comment by aebruno** [comment]
> I guess the patch should be in (a different person fixed it however): https://github.com/systemd/mkosi/pull/432/files
> 

Yes, it's been a while since I've merged in the latest mkosi upstream. I plan to do that very soon.

**Comment by lzap** [comment]
Ah, hmmm, something is still not right. Investigating:

```
dracut: *** Creating image file '/srv/pxelive/initramfs.img' ***
dracut: *** Creating initramfs image file '/srv/pxelive/initramfs.img' done ***
‣ Running postinstall script complete.
‣ Unmounting Package Cache...
‣ Unmounting Package Cache complete.
‣ Cleaning tdnf metadata...
‣ Resetting machine ID...
‣ Resetting machine ID complete.
‣ Removing random seed...
‣ Removing random seed complete.
‣ Running finalize script...
2021-05-25 17:13:30 [CRITICAL] Failed to find image name. Please provide an image name
‣ Unmounting image...
‣ Unmounting image complete.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/mkosi/__main__.py", line 31, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/mkosi/__main__.py", line 25, in main
    run_verb(a)
  File "/usr/lib/python3.9/site-packages/mkosi/__init__.py", line 6367, in run_verb
    build_stuff(args)
  File "/usr/lib/python3.9/site-packages/mkosi/__init__.py", line 6014, in build_stuff
    raw, tar, root_hash, sshkey = build_image(args, root, do_run_build_script=False, cleanup=True)
  File "/usr/lib/python3.9/site-packages/mkosi/__init__.py", line 5814, in build_image
    run_finalize_script(args, root, do_run_build_script, for_cache)
  File "/usr/lib/python3.9/site-packages/mkosi/__init__.py", line 3090, in run_finalize_script
    run([args.finalize_script, verb], env=env)
  File "/usr/lib/python3.9/site-packages/mkosi/__init__.py", line 207, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, **kwargs)
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/grendel-images/mkosi.finalize', 'final']' returned non-zero exit status 1.
```

**Comment by aebruno** [comment]
I believe you'll also need to patch this line: https://github.com/ubccr/mkosi/commit/04dc03071d1c484b6a83856b0e3f5ee03fa33a6e#diff-74e3e43cb6c00639d4d4dea5cf84ae14d112a85ae5e0850bd5fd85d2e0f854e3R2269

That will pass the OUTPUT_DIR to the finalize script. Looks like that may be what you're hitting? I just tested on my system and was able to build the centos8 image ok.

**Comment by lzap** [comment]
Ah I guess it is named OUTPUTDIR now:

https://github.com/systemd/mkosi/blob/6ba17b43d3807a6cf963ad79eb6381fd787a5a3b/mkosi/__init__.py#L3395

Lemme update this.

**Comment by aebruno** [comment]
> Ah I guess it is named OUTPUTDIR now:

Nice, yeah I really need to sync up with latest mkosi. It's on the (long) TODO list
